<?php
    $level="../";
    $isIndex=false;
    $isMuaHang=false;
    $isChiTietSanPham=false;
    $isCart=false;
    $isLienHe=false;
    $isThongTin=false;
    $isDangNhap=false;
    $isDangKy=false;
    $isThongTinTK=true;
    require_once($level."layout.php");
?>