<?php
    define('head_path','head/');
    define('body_path','body/');
    define('footer_path','footer/');
    define('css_path','assets/css/');
    define('css_path_2','assets/css2/');
    define('img_path','assets/img/');
    define('js_path','assets/js/');
    define('js_path_2','assets/js2/');
?>