<?php
    define('head_path','head/');
    define('body_path','body/');
    define('footer_path','footer/');
    define('css_path','assets/css/');
    define('css_path_2','assets/css2/');
    define('img_path','assets/img/');
    define('comp_path','comp/');
    define('lib_path','lib/');
    define('js_path','assets/js/');
    define('js_path_2','assets/js2/');
    define('api_path','api/');
?>