<?php
    $level="";
    $isIndex=true;
    $isMuaHang=false;
    $isChiTietSanPham=false;
    $isCart=false;
    $isLienHe=false;
    $isThongTin=false;
    $isDangNhap=false;
    $isDangKy=false;
    $isThongTinTK=false;
    require_once($level."layout.php");
?>